Repository jenkinsci/security-inspector-plugin, pull requests merged in 2022-05, with the labels that each got.

#12 Adapt icon path removal from core
  .gitignore
  src/main/resources/org/jenkinsci/plugins/securityinspector/model/ReportBuilder/createReport.jelly
  src/main/resources/org/jenkinsci/plugins/securityinspector/model/ReportBuilder/report.jelly
Labels: bug

#9 Use GitHub as a source of plugin documentation
  pom.xml
Labels: documentation

#13 feat: Enable dependabot and CD
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#14 Update screenshots
  docs/images/FilterForOneUserAndJobs.png
  docs/images/ReportForUser1ForItems.png
  docs/images/ReportForUserAndJobs.png
  docs/images/SecurityInspectorIndex.png
  src/main/resources/org/jenkinsci/plugins/securityinspector/SecurityInspectorAction/index.jelly
Labels: enhancement
